---
- name: Install vagrant plugins for libvirt provider
  ansible.builtin.command:
    cmd: vagrant plugin install {{ item }}
  loop:
    - vagrant-libvirt
    - vagrant-mutate
    - nokogiri

- name: Set vagrant default provider to libvirt
  ansible.builtin.command:
    cmd: export VAGRANT_DEFAULT_PROVIDER=libvirt

- name: Download the boxes you frequently use
  ansible.builtin.command:
    cmd: vagrant box add {{ item }} --provider libvirt
  loop:
    - generic/centos9s
    - archlinux/archlinux
    - opensuse/Tumbleweed.x86_64

- name: Mutate boxes
  ansible.builtin.command:
    cmd: |
      vagrant box add {{ item }} --provider virtualbox
      vagrant mutate {{ item }} libvirt
  loop:
    - hashicorp/bionic64
