Vagrant.configure("2") do |config|
  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "ubuntu/jammy64"
    machine1.vm.host_name = "machine1"
    machine1.vm.network "private_network", ip: "192.168.56.13"
    machine1.vm.provider "virtualbox" do |v|
      v.name = "machine_home_1"
      v.cpus = "4"
      v.memory = "10240"
    end
    machine1.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/home_1.yml"
      ansible.extra_vars = "vars.yml"
    end
    machine1.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    machine1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
  #config.vm.define "machine2" do |machine2|
  #  machine2.vm.box = "ubuntu/jammy64"
  #  machine2.vm.host_name = "machine2"
  #  machine2.vm.provision "ansible" do |ansible|
  #    ansible.playbook = "../ansible/playbooks/playbook.yml"
  #    #ansible.inventory_path = "../ansible/homelab"
  #  end
  #end
end
