Vagrant.configure("2") do |config|
  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "ubuntu/jammy64"
    machine1.vm.host_name = "machine1"
    machine1.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/playbook.yml"
      #ansible.inventory_path = "../ansible/homelab"
    end
  end
  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "ubuntu/jammy64"
    machine2.vm.host_name = "machine2"
    machine2.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/playbook.yml"
      #ansible.inventory_path = "../ansible/homelab"
    end
  end
  config.vm.define "machine3" do |machine3|
    machine3.vm.box = "ubuntu/jammy64"
    machine3.vm.host_name = "machine3"
    machine3.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/playbook.yml"
      #333ansible.inventory_path = "../ansible/homelab"
    end
  end
end
