galaxy_info:
  author: The Integrative
  description: CLI tools I like to use
  company: The Integrative

  license: license GPL-3.0-or-later

  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
      - all

  galaxy_tags: []

dependencies: []
