---
- hosts: "{{ variable_host | default('pc') }}"
  become: true
  vars:
    user_name: "theintegrative"
    user_home: "/home/{{ user_name }}/"
  roles:
    - cli_tools
    - archer_T3U
    - virt-manager-terraform
    - docker
