---
- hosts: pc
  vars:
    user_name: "theintegrative"
    user_home: "/home/{{ user_name }}/"
  roles:
    - cli_tools
    - archer_T3U
      #- virt-manager-terraform

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
    
    - name: Add the user "{{ user_name }}" to group docker
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: docker
        append: true
