---
- name: Install libvirt and ansible
  ansible.builtin.apt:
    name: 
      - virt-manager
      - ansible
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Configure services that run on your system
  ansible.builtin.service:
    name: libvirtd
    enabled: true
    state: restarted

- name: Add settings for libvirt to work with terraform-provider-libvirt
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    line: 'security_driver = "none"'

- name: Add libvirt to user groups
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: libvirt
    append: yes

- name: Download image files
  ansible.builtin.get_url:
    url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2 
    dest: /var/lib/libvirt/images/CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2
