---
- name: Install kvm
  ansible.builtin.apt:
    name:
      - virt-manager
    state: latest

- name: Enable service libvirt, and start if not started
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: adding existing user ansible to group libvirt/-qemu
  user:
    name: "theintegrative"
    groups: libvirt,libvirt-qemu
    append: yes

- name: Initialise microstack
  ansible.builtin.shell: "{{ item }}"
  loop:
    - snap install microstack --beta
    - microstack init --auto --control
    - snap install openstackclients
